service: nhsvac
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-2
  memorySize: 512

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource: "*"

functions:
  checkAge:
    handler: handler.checkAge
    events:
      - schedule: cron(0/15 * * * ? *)
    environment:
      AGE_TARGET: 31
      PHONE_NUMBER: 44XXXXXXXXXX
